### ISSUE TITLE
No route to host on macOS 15.0.1 Sequoira (firewall issue)

### ISSUE THREAD

**Issue by stijnve** [deskflow/deskflow#7794]
### Project

Deskflow

### Deskflow version number

1.17.0

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland known issues and my issue is new
- [X] I am not using Wayland on Linux

### Signing on macOS

- [X] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [X] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

macOS 15.0.1

### Deskflow configuration

- Linux server, macOS Client

### What steps will reproduce the problem?

- installed client application on macOS & authorized it
- connects to server
- reboot Mac, get errors "no route to host"
- toggle Deskflow off and on in Privacy & Security, Local Network restrictions
- connects again to the server

**Comment by nbolton** [comment]
Thanks for reporting. Does TLS being on/off in Deskflow make any difference?

**Comment by zhurai** [comment]
Let's also try to narrow out some possible networking/routing issues. 

Is the macbook able to reach your linux box (and visa-versa) separately via icmp?  e.g. via ping/mtr?  

Does doing `telnet linux-ip port#` work by showing that you connected to the linux that way? If not, is the server up on linux? running `netstat -an | grep LISTEN | grep port#` on the linux box might help

Is the macbook running any separate VPN's? If so, are any of them changing the gateway for the default route/0.0.0.0 to itself?  If so, you might need to change the settings to allow your LAN ip addresses to use the router gateway.

**Comment by stijnve** [comment]
Hi guys, 

TLS on or off makes no difference.
Ping and telnet keep working just fine.

All is running on a standalone network, no routers, no firewalls, all static IP’s.

**Comment by nbolton** [comment]
> TLS on or off makes no difference. Ping and telnet keep working just fine.
> 
> All is running on a standalone network, no routers, no firewalls, all static IP’s.

Thanks. I know it sounds risky but are you able to turn off the Sequoira firewall for a brief period to confirm that the problem goes away? We're trying to isolate the problem to the firewall. If you need a firewall, you can install something like [LittleSnitch](https://obdev.at/products/littlesnitch/index.html) which AFAIK has no issues with Deskflow.

**Comment by sithlord48** [comment]
hmm Working fine on my mac.(15.0.1)
can you try this
Remove all the accessibility settings for deskflow and re run the application to have mac os reask about the permissions. 
I have to do this for each new version. or it will just siletly fail to not use the accessibility permission

**Comment by nbolton** [comment]
> accessibility permission

I believe this is a firewall issue in Sequoia:
- https://symless.com/synergy/help/macos-15-sequoia-firewall-breaks-network-connection
- https://forums.symless.com/topic/7704-loss-of-connection-and-focus-with-macos-sequoia/
- https://mjtsai.com/blog/2024/09/18/macos-firewall-regressions-in-sequoia/
- https://techcrunch.com/2024/09/19/apples-new-macos-sequoia-update-is-breaking-some-cybersecurity-tools/
- https://www.theregister.com/2024/09/23/security_in_brief/
- https://discussions.apple.com/thread/255765230?sortBy=rank
- https://uk.pcmag.com/security/154463/macos-sequoia-causing-vpn-web-browsing-antivirus-software-problems
- https://support.apple.com/en-us/120283

**Comment by Dentrax** [comment]
I can confirm this. I didn't see that Firewall issue on MacOS 15 and I just upgraded... Eventually Deskflow completely broken.

I was following the [Synergy's doc](https://symless.com/synergy/help/macos-15-sequoia-firewall-breaks-network-connection) but there is no such `deskflow` apps under `Local Network` privacy settings.

Deskflow server logs are:
```
[2024-10-23T14:50:41] INFO: starting core server process (desktop mode)
[2024-10-23T14:50:41] INFO: core config file: /Users/furkan/Library/Preferences/Deskflow/deskflow-server.conf
[2024-10-23T14:50:41] INFO: running command: /Applications/Deskflow.app/Contents/MacOS/deskflow-server -f --no-tray --debug INFO --name Furkans-MacBook-Pro.local --address :24800 -c /Users/furkan/Library/Preferences/Deskflow/deskflow-server.conf
[2024-10-23T14:50:41] NOTE: clipboard sharing is disabled
[2024-10-23T14:50:41] NOTE: started server, waiting for clients
2024-10-23 14:50:41.279 deskflow-server[13188:81738] starting cocoa loop
```

I don't think this is a Deskflow bug. Is there anything else that we can do besides waiting a fix version of macOS? Thank you Apple...

**Comment by nbolton** [comment]
> anything else that we can do besides waiting a fix version of macOS? Thank you Apple...

Can you disable the Sequoia firewall and use [LittleSnitch](https://obdev.at/products/littlesnitch/index.html) instead. If so, make sure you "[Allow GUI scripting access to Little Snitch](https://www.obdev.at/support/littlesnitch/bwpot#:~:text=If%20you%20do%20need%20remote,Snitch%20Configuration%20%3E%20Preferences%20%3E%20Security.)"

**Comment by Dentrax** [comment]
> Can you disable the Sequoia firewall

I don't think I have permission to do that since it's controlled by a profile. I've added the deskflow apps to allowlist but it doesn't seem to work either.


<img width="484" alt="Screenshot 2024-10-23 at 16 00 28" src="https://github.com/user-attachments/assets/5ca37303-955b-4afb-8534-856c1c9ccd34">

**Comment by stijnve** [comment]
Since the Macs in question don't have internet access and are used on LAN only, the firewall is off already....
Removed all the accessibility settings for Deskflow multiple times, that didn't help either.

**Comment by nbolton** [comment]
> the firewall is off already

Now I'm confused. I wonder if macOS Sequoia network security spans further than the firewall...

**Comment by rexzhang** [comment]
Problems persist after Host update to mac OS 15.1.

- version: deskflow_1.17.0+r1_mac_x64.dmg

<img width="495" alt="截屏2024-10-29 18 13 34" src="https://github.com/user-attachments/assets/80658696-754b-4b2a-ae4d-200328e961fb">

**Comment by iamajohn** [comment]
I am getting ssl issue https://github.com/deskflow/deskflow/issues/7830 but disabling firewall helps

**Comment by nbolton** [comment]
> > the firewall is off already
> 
> Now I'm confused. I wonder if macOS Sequoia network security spans further than the firewall...

I'm hearing reports that macOS 15.1 (not 15.0.1) fixes the network issues with Deskflow/Synergy. Those experiencing issues please try macOS 15.1 and let me know if this solves your problem.

**Comment by Dentrax** [comment]
It seems upgrading to `macOS 15.1` fixed the issue for me! (Need to update the server IP on the client) Firewall is enabled.

**Comment by nbolton** [comment]
> 🎉 It seems upgrading to `macOS 15.1` fixed the issue for me! (Need to update the server IP on the client) Firewall is enabled.

That's amazing to hear! I'm hearing this a lot now. Good on Apple for fixing this so quickly.

I'm still scratching my head why some people still report it not working on macOS 15.1 and some report it fixed.

**Comment by nbolton** [comment]
Many people saying that 15.1 (not 15.0.1) fixes this.

Closing tentatively with solution. If anyone is still having problems, let me know.

**Solution:** Upgrade to MacOS 15.1 (not 15.0.1) ✔️

**Comment by Dentrax** [comment]
FWIW, we should drop a note in the [Wiki](https://github.com/deskflow/deskflow/wiki/Running-on-macOS).

**Comment by nbolton** [comment]
> FWIW, we should drop a note in the [Wiki](https://github.com/deskflow/deskflow/wiki/Running-on-macOS).

Done, thanks for the tip.

**Comment by Mzdyl** [comment]
Encountered the same issue in 15.2 beta, along with some potentially helpful information. Did not experience this issue with v1.17.0, but encountered it after updating to v1.17.1.

**Comment by nbolton** [comment]
> Reverting to v1.7.0 resolved the issue.

I'd be surprised if it was related to the version. I wonder if this is because the 'Local Network' entry you approved is based on the first .app bundle you installed.

**Comment by Mzdyl** [comment]
> > Reverting to v1.7.0 resolved the issue.
> 
> I'd be surprised if it was related to the version. I wonder if this is because the 'Local Network' entry you approved is based on the first .app bundle you installed.

I don’t have a clear memory of whether I applied for and granted ‘Local Network’ for the two versions. I don’t remember being prompted to grant ‘Local Network’ access.

I just tried reinstalling the software again to test, but both versions are working fine. It might be due to the system update to 15.2 beta3 today, so I can’t provide more information.

**Comment by iamajohn** [comment]
Downgrading to 1.17.0+r1 (44bd69fd) on both mac didnt help in my case.

**Comment by tjuerges** [comment]
Indeed 1.17.1 feels like a regression. Same issue here on two macs (both on macOS 15.1); firewall or TLS setting did not change a thing.

Went back to 1.17.0.74 (71e74735) and everything worked again.

**Comment by nbolton** [comment]
> Indeed 1.17.1 feels like a regression.

I think the issue comes from using a different `.app` bundle and is probably not related to the particular version/build or any changes in 1.17.1.

Please try un-setting and resetting your 'Local Network‍' settings for Synergy in macOS Settings.

1. Open the Apple menu‍
1. Select System Settings‍
1. Go to Privacy & Security
1. ‍Find Local Network‍
1. Locate Synergy in the list
1. Toggle it to On to grant access

**Comment by tjuerges** [comment]
> Please try un-setting and resetting your 'Local Network‍' settings for Synergy in macOS Settings.
> 
> 1. Open the Apple menu‍
> 2. Select System Settings‍
> 3. Go to Privacy & Security
> 4. ‍Find Local Network‍
> 5. Locate Synergy in the list
> 6. Toggle it to Off
> 7. Toggle it to On to grant access

Done that. Even removed Synergy entirely. Not a chance.

**Comment by nbolton** [comment]
How about:
1. Remove Deskflow/Synergy from 'Local Network‍'
1. Delete the Deskflow/Synergy app
1. Reboot
2. Reinstall Deskflow/Synergy
3. Re-enable Deskflow/Synergy in 'Local Network‍'

**Comment by robertlabrie** [comment]
Hey I know this is an old thread, but I googled my way here and wanted to add a datapoint. I was using barrier when this started happening and switched to deskflow because it's still being actively maintained but the issue persists. Sharing because it was a clean install of deskflow post MacOS 15.1 upgrade and the OS had never seen the app bundle before. 

Its intermittent, every 30 minutes or so the client disconnects, goes into a (dis)/connect loop for about 30 seconds then works normally for a while. 

Server: Windows 11, Client: MacOS 15.1. TLS: Disabled. Version: 1.17.1.0 (a80cea3c)

**Comment by akshayje** [comment]
Although this issue is closed posting comment for those who still have their issue unresolved. Adding Deskflow to System Settings>Privacy and security> Developer Tools solved the issue for me.
