### ISSUE TITLE
WARNING: failed to determine current keyboard layout

### ISSUE THREAD

**Issue by Slient1802** [deskflow/deskflow#7854]
### Project

Deskflow

### Deskflow version number

1.17.0+r1 (44bd69fd)
Deskflow: 1.19.0.11 (94207095)
Qt: 6.7.2
System: Windows 11 Version 23H2

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [X] Windows
- [ ] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [x] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [x] I am not using macOS

### Continuous build

- [X] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

Window 11 - window 10

### Deskflow configuration

Window 11 sever. Window 10 client (window 11 has 2 monitors and on the right of Window 10 - 1 monitor)

### What steps will reproduce the problem?

_Revised:_
1. Start deskflow
2. Turn off "use of background services (daemon)" in Service
3. Change TLS encryption to 4096
4. Right-click at anything, and then the program seemed to freeze (mouse + keyboard) on my client PC only (with the context box open) but I can still move the mouse outside of my client PC back to the server PC (working)
5. Move the mouse back to the server PC
6. Using my client's PC mouse to escape from that context box
7. Using my keyboard and then the error pops up (```WARNING: failed to determine current keyboard layout```)

PS: The program somehow works again sometimes after countless reconnecting the program link and rebooting both the client and the server PC and the mouse and the keyboard suddenly at some random time the program just decided to disconnect until I use my client PC to move around/ unlink and relink it again. 

_Original:_
1. Start deskflow
2. Turn off "use of background services (daemon)" in Service
3. Change TLS encryption into 4096
4. Using the shortcut key or right click at anything (e.g., Alt + tab, Alt + F4, Ctrl + Shift + Esc,... ). in the client computer (window 10), and the mouse and keyboard can't be used anymore until I move the mouse back to the server PC (working normally ) or using the mouse client PC to esc of that right click box then the program seem to working again

### Log output

```shell
[2024-11-04T22:28:19] INFO: starting core server process (desktop mode)
[2024-11-04T22:28:20] INFO: core config file: C:/Users/ADMIN/AppData/Local/Deskflow/deskflow-server.conf
[2024-11-04T22:28:20] INFO: log file: C:/Users/ADMIN/deskflow.log
[2024-11-04T22:28:20] INFO: running command: "C:/Program Files/Deskflow/deskflow-server.exe" -f --no-tray --debug INFO --name RH-Lap --enable-crypto --profile-dir C:/Users/ADMIN/AppData/Local --prevent-sleep --log C:/Users/ADMIN/deskflow.log --address :24800 -c C:/Users/ADMIN/AppData/Local/Deskflow/deskflow-server.conf --tls-cert C:/Users/ADMIN/AppData/Local/Deskflow/SSL/Deskflow.pem
[2024-11-04T22:28:20] WARNING: failed to register hotkey ScrollLock (id=ef14 mask=0000)
[2024-11-04T22:28:20] NOTE: started server, waiting for clients
[2024-11-04T22:31:14] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:15] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:15] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:15] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:15] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:15] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:16] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:17] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:17] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:17] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:17] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:17] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:18] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:18] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:18] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:18] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:19] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:19] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:19] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:19] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:19] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:19] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:20] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:21] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:21] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:22] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:22] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:22] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:22] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:22] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:22] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:22] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:22] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:22] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:23] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:23] WARNING: failed to determine current keyboard layout
[2024-11-04T22:31:23] WARNING: failed to determine current keyboard layout
```

### Additional information

When using my client PC, the program seems to work normally with the mouse but I can't type anything. 
And I can't use Unikey/ EVkey on the client side to type some words (eg: á,à,ạ,ă,ẵ...)

**Comment by nbolton** [comment]
Thanks for the bug report. I'm finding this a bit hard to follow:
> Using the shortcut key or right click at anything (e.g., Alt + tab, Alt + F4, Ctrl + Shift + Esc,... ). in the client computer (window 10), and the mouse and keyboard can't be used anymore until I move the mouse back to the server PC (working normally ) or using the mouse client PC to esc of that right click box then the program seem to working again

Are you able to break that up into simple reproducible steps?

**Comment by Slient1802** [comment]
> Thanks for the bug report. I'm finding this a bit hard to follow:
> 
> > Using the shortcut key or right click at anything (e.g., Alt + tab, Alt + F4, Ctrl + Shift + Esc,... ). in the client computer (window 10), and the mouse and keyboard can't be used anymore until I move the mouse back to the server PC (working normally ) or using the mouse client PC to esc of that right click box then the program seem to working again
> 
> Are you able to break that up into simple reproducible steps?

Sorry for my poor English, I will try my best to break that up into more simple reproducible steps:
1. Right-click at anything, and then the program seemed to freeze (mouse + keyboard) on my client PC only (with the context box open) but I can still move the mouse outside of my client PC back to the server PC (working)
2. Move the mouse back to the server PC
3. Using my client's PC mouse to escape from that context box
4. Using my keyboard and then the error pops up (```WARNING: failed to determine current keyboard layout```)
PS: The program somehow works again after countless of reconnecting the program link and reboot both PC, but I can't use Unikey/ EVkey to type special words anymore 💀 (e.g., á,à,ạ ă,ẵ...).

**Comment by nbolton** [comment]
> Or maybe there is a bug with TLS encryption 4096 is unstable so the program starts to reconnect/disconnect countless times?

I'm trying to figure out why 'TLS encryption 4096' is relevant. Is it that it works under a different key length? Does turning TLS on/off make a difference?

**Comment by Slient1802** [comment]
> > Or maybe there is a bug with TLS encryption 4096 is unstable so the program starts to reconnect/disconnect countless times?
> 
> I'm trying to figure out why 'TLS encryption 4096' is relevant. Is it that it works under a different key length? Does turning TLS on/off make a difference?

Let me try turning TLS on/ off and under a different key length

**Comment by Slient1802** [comment]
I have a question: Is it normal for the logs constantly prompting this:
```INFO: network encryption protocol: TLSv1.3
[2024-11-06T22:36:14] NOTE: accepted client connection
[2024-11-06T22:36:16] NOTE: new client disconnected
[2024-11-06T22:36:17] INFO: accepted secure socket
[2024-11-06T22:36:17] INFO: network encryption protocol: TLSv1.3
[2024-11-06T22:36:17] NOTE: accepted client connection
[2024-11-06T22:36:19] NOTE: new client disconnected
[2024-11-06T22:36:20] INFO: accepted secure socket```

**Comment by nbolton** [comment]
> I have a question: Is it normal for the logs constantly prompting this:
> `INFO: network encryption protocol: TLSv1.3`

That generally ties in with `accepted client connection`, so you should only see this once. 

Perhaps the client process is continuously crashing?

**Comment by Slient1802** [comment]
> > I have a question: Is it normal for the logs constantly prompting this:
> > `INFO: network encryption protocol: TLSv1.3`
> 
> That generally ties in with `accepted client connection`, so you should only see this once.
> 
> Perhaps the client process is continuously crashing?

I think so, the program somehow continuously reconnects/disconnects and yet its still working if I turn it on ? :D???

**Comment by Slient1802** [comment]
And I also notice that there is a delay (flash many time when I switch between sever & client)
Logs constantly prompt during flash mouse:
```
[2024-11-06T23:12:11] INFO: switch from "RH-Lap" to "Ruan-Slients-PC" at 1919,770
[2024-11-06T23:12:11] INFO: leaving screen
[2024-11-06T23:12:11] INFO: bitmap: 3842x1871 32
[2024-11-06T23:12:11] INFO: convert image from: depth=32 comp=3
[2024-11-06T23:12:11] INFO: bitmap: 3842x1871 32
[2024-11-06T23:12:11] INFO: convert image from: depth=32 comp=3
[2024-11-06T23:12:11] INFO: switch from "Ruan-Slients-PC" to "RH-Lap" at 1,1541
[2024-11-06T23:12:11] INFO: entering screen
[2024-11-06T23:12:11] INFO: switch from "RH-Lap" to "Ruan-Slients-PC" at 1919,770
[2024-11-06T23:12:11] INFO: leaving screen
[2024-11-06T23:12:11] INFO: bitmap: 3842x1871 32
[2024-11-06T23:12:11] INFO: convert image from: depth=32 comp=3
[2024-11-06T23:12:11] INFO: bitmap: 3842x1871 32
[2024-11-06T23:12:11] INFO: convert image from: depth=32 comp=3
```

**Comment by nbolton** [comment]
From your latest log, it seems to be working, is this the case?

Looks like you've figured out that the TLS settings need to match on all computers.

**Comment by Slient1802** [comment]
> From your latest log, it seems to be working, is this the case?
> 
> Looks like you've figured out that the TLS settings need to match on all computers.

Yes, I want to provide the solution for how I got the program seems to work normally when I configure 2 computers with the same key length TLS and turn on "use of background services (daemon): Always elevate" in Service. 
However, the program still randomly has the bug after sometime ```WARNING: failed to determine current keyboard layout```. 
``` 
[2024-11-07T19:36:18] NOTE: client "Ruan-Slients-PC" has connected
[2024-11-07T19:36:22] WARNING: failed to determine current keyboard layout
[2024-11-07T19:36:22] WARNING: failed to determine current keyboard layout
[2024-11-07T19:36:23] WARNING: failed to determine current keyboard layout
[2024-11-07T19:36:23] WARNING: failed to determine current keyboard layout
[2024-11-07T19:36:24] WARNING: failed to determine current keyboard layout
[2024-11-07T19:36:24] WARNING: failed to determine current keyboard layout
[2024-11-07T19:36:24] WARNING: failed to determine current keyboard layout
[2024-11-07T19:36:24] WARNING: failed to determine current keyboard layout
```

**Comment by Slient1802** [comment]
> From your latest log, it seems to be working, is this the case?
> 
> Looks like you've figured out that the TLS settings need to match on all computers.

Yes, I want to provide you more about the bug I got and how I got the program seems to work normally when I configure 2 computers with the same key length TLS and turn on "use of background services (daemon): Always elevate" in Service. 
However, the program still randomly has the bug after some time ```WARNING: failed to determine current keyboard layout```. 
``` 
[2024-11-07T19:36:18] NOTE: client "Ruan-Slients-PC" has connected
[2024-11-07T19:36:22] WARNING: failed to determine current keyboard layout
[2024-11-07T19:36:22] WARNING: failed to determine current keyboard layout
[2024-11-07T19:36:23] WARNING: failed to determine current keyboard layout
[2024-11-07T19:36:23] WARNING: failed to determine current keyboard layout
[2024-11-07T19:36:24] WARNING: failed to determine current keyboard layout
[2024-11-07T19:36:24] WARNING: failed to determine current keyboard layout
[2024-11-07T19:36:24] WARNING: failed to determine current keyboard layout
[2024-11-07T19:36:24] WARNING: failed to determine current keyboard layout
```
It seems that the connection is already successful but the client side still has the bug ```WARNING: failed to determine current keyboard layout``` and when that happens I can't type anything but still able to move and click on stuff in the client PC.
PS: I didn't change anything in the setting but the program seems to not working at random times.

**Comment by Slient1802** [comment]
Update: I have updated both my client and server to version 1.17.1.0 (a80cea3c) but the problem is still there but now it prompt every time I switch from sever into client
Server logs:
```
[2024-11-11T23:53:12] INFO: switch from "Ruan-Slients-PC" to "RH-Lap" at 29,1179
[2024-11-11T23:53:12] INFO: entering screen
[2024-11-11T23:53:12] INFO: switch from "RH-Lap" to "Ruan-Slients-PC" at 1919,591
[2024-11-11T23:53:12] INFO: leaving screen
[2024-11-11T23:53:12] DEBUG: open clipboard
[2024-11-11T23:53:12] DEBUG: close clipboard
[2024-11-11T23:53:12] DEBUG: ignored screen "RH-Lap" update of clipboard 0 (unchanged)
[2024-11-11T23:53:12] DEBUG: open clipboard
[2024-11-11T23:53:12] DEBUG: close clipboard
[2024-11-11T23:53:12] DEBUG: ignored screen "RH-Lap" update of clipboard 1 (unchanged)
[2024-11-11T23:53:12] DEBUG: dropped bogus delta motion: -1934,+106
[2024-11-11T23:53:12] INFO: switch from "Ruan-Slients-PC" to "RH-Lap" at 4,1181
[2024-11-11T23:53:12] INFO: entering screen
[2024-11-11T23:53:12] INFO: switch from "RH-Lap" to "Ruan-Slients-PC" at 1919,591
[2024-11-11T23:53:12] INFO: leaving screen
[2024-11-11T23:53:12] WARNING: failed to determine current keyboard layout
[2024-11-11T23:53:12] DEBUG: open clipboard
[2024-11-11T23:53:12] DEBUG: close clipboard
[2024-11-11T23:53:12] DEBUG: ignored screen "RH-Lap" update of clipboard 0 (unchanged)
[2024-11-11T23:53:12] DEBUG: open clipboard
[2024-11-11T23:53:12] DEBUG: close clipboard
[2024-11-11T23:53:12] DEBUG: ignored screen "RH-Lap" update of clipboard 1 (unchanged)
[2024-11-11T23:53:12] DEBUG: dropped bogus delta motion: -1934,+107
[2024-11-11T23:54:04] INFO: switch from "Ruan-Slients-PC" to "RH-Lap" at 8,1297
[2024-11-11T23:54:04] INFO: entering screen
[2024-11-11T23:54:05] INFO: switch from "RH-Lap" to "Ruan-Slients-PC" at 1919,716
[2024-11-11T23:54:05] INFO: leaving screen
[2024-11-11T23:54:05] WARNING: failed to determine current keyboard layout
[2024-11-11T23:54:05] DEBUG: open clipboard
[2024-11-11T23:54:05] DEBUG: close clipboard
[2024-11-11T23:54:05] DEBUG: ignored screen "RH-Lap" update of clipboard 0 (unchanged)
[2024-11-11T23:54:05] DEBUG: open clipboard
[2024-11-11T23:54:05] DEBUG: close clipboard
[2024-11-11T23:54:05] DEBUG: ignored screen "RH-Lap" update of clipboard 1 (unchanged)
[2024-11-11T23:54:07] INFO: switch from "Ruan-Slients-PC" to "RH-Lap" at 7,1293
[2024-11-11T23:54:07] INFO: entering screen
[2024-11-11T23:54:08] INFO: switch from "RH-Lap" to "Ruan-Slients-PC" at 1919,762
[2024-11-11T23:54:08] INFO: leaving screen
[2024-11-11T23:54:08] WARNING: failed to determine current keyboard layout
[2024-11-11T23:54:08] DEBUG: open clipboard
[2024-11-11T23:54:08] DEBUG: close clipboard
```

**Comment by nmofonseca** [comment]
Hello,

I am having a similar issue but my setup I think it's different, I don't see any errors in the log though but certain keys don't work on the client side, e.g. square brackets, the composite key.

I am using Windows 11 (23H2)  as the server and Ubuntu 24.04.01 as the client.

Maybe is just configuration but I don't seem to be able to find what could be.

**Comment by Slient1802** [comment]
update: this bug still appears in Deskflow: 1.19.0.11 (94207095)
Qt: 6.7.2
System: Windows 11 Version 23H2
logs:
```
[2025-02-08T16:36:06] INFO: starting core server process (service mode)
[2025-02-08T16:36:06] INFO: core config file: C:/Users/ADMIN/AppData/Local/Deskflow/deskflow-server.conf
[2025-02-08T16:36:06] INFO: log file: C:/Users/ADMIN/deskflow.log
[2025-02-08T16:36:06] INFO: connecting to background service...
[2025-02-08T16:34:32] DEBUG: adopting new buffer
[2025-02-08T16:34:32] INFO: using last known command: "C:/Program Files/Deskflow/deskflow-server.exe" -f --debug DEBUG --name RH-Lap --ipc --enable-crypto --profile-dir C:/Users/ADMIN/AppData/Local --prevent-sleep --log C:/Users/ADMIN/deskflow.log --address :24800 -c C:/Users/ADMIN/AppData/Local/Deskflow/deskflow-server.conf --tls-cert C:/Users/ADMIN/AppData/Local/Deskflow/tls/deskflow.pem
[2025-02-08T16:34:32] INFO: service command updated
[2025-02-08T16:34:32] DEBUG: event queue is ready
[2025-02-08T16:34:32] DEBUG: found sas.dll
[2025-02-08T16:34:32] DEBUG: starting command as session user
[2025-02-08T16:34:32] FATAL: failed to get active desktop name
[2025-02-08T16:34:32] DEBUG: getting elevated token, elevation required
[2025-02-08T16:34:32] DEBUG: found winlogon.exe in session 1
[2025-02-08T16:34:32] DEBUG: got token 612, duplicating
[2025-02-08T16:34:32] DEBUG: duplicated, new token: 616
[2025-02-08T16:34:32] INFO: starting new process
[2025-02-08T16:34:32] DEBUG: opening new socket: 98F23BB0
[2025-02-08T16:34:32] DEBUG: accepted ipc client connection
[2025-02-08T16:34:32] DEBUG: start ipc handle data
[2025-02-08T16:34:32] DEBUG: ipc read: IHEL
[2025-02-08T16:34:32] DEBUG: finished ipc handle data
[2025-02-08T16:34:32] DEBUG: ipc hello, type=node
[2025-02-08T16:34:32] INFO: service status: active
[2025-02-08T16:34:32] DEBUG: opening configuration "C:/Users/ADMIN/AppData/Local/Deskflow/deskflow-server.conf"
[2025-02-08T16:34:32] DEBUG: configuration read successfully
[2025-02-08T16:34:32] WARNING: failed to determine current keyboard layout
[2025-02-08T16:34:32] DEBUG: screen shape: 0,0 5760x2160 (multi-monitor)
[2025-02-08T16:34:32] DEBUG: window is 0x000101ea
[2025-02-08T16:34:32] DEBUG: unable to use desktop as file drag-drop target, code=2
[2025-02-08T16:34:32] DEBUG: adopting new buffer
[2025-02-08T16:34:32] DEBUG: opened display
[2025-02-08T16:34:32] DEBUG: active sides: 2
[2025-02-08T16:34:32] DEBUG: active sides: 2
[2025-02-08T16:34:32] DEBUG: desk Winlogon window is 0x00010200
[2025-02-08T16:34:32] DEBUG: switched to desk "Winlogon"
[2025-02-08T16:34:32] DEBUG: desktop is now accessible
[2025-02-08T16:34:32] DEBUG: registered hotkey ScrollLock (id=ef14 mask=0000) as id=1
[2025-02-08T16:34:32] NOTE: started server, waiting for clients
[2025-02-08T16:34:32] DEBUG: opening new socket: E8628E70
[2025-02-08T16:34:32] DEBUG: event queue is ready
[2025-02-08T16:34:32] DEBUG: add pending events to buffer
[2025-02-08T16:34:32] DEBUG: screen "RH-Lap" shape changed
[2025-02-08T16:34:33] DEBUG: started core process from daemon
[2025-02-08T16:34:38] DEBUG: desk Default window is 0x000403ec
[2025-02-08T16:34:38] DEBUG: switched to desk "Default"
[2025-02-08T16:36:06] DEBUG: opening new socket: 98F33720
[2025-02-08T16:36:06] DEBUG: accepted ipc client connection
[2025-02-08T16:36:06] DEBUG: start ipc handle data
[2025-02-08T16:36:06] DEBUG: ipc read: IHEL
[2025-02-08T16:36:06] DEBUG: finished ipc handle data
[2025-02-08T16:36:06] DEBUG: ipc hello, type=gui
[2025-02-08T16:36:06] DEBUG: sending ipc hello back
[2025-02-08T16:36:06] INFO: starting core server process (service mode)
[2025-02-08T16:36:06] INFO: core config file: C:/Users/ADMIN/AppData/Local/Deskflow/deskflow-server.conf
[2025-02-08T16:36:06] INFO: log file: C:/Users/ADMIN/deskflow.log
[2025-02-08T16:36:06] INFO: running command: "C:/Program Files/Deskflow/deskflow-server.exe" -f --debug DEBUG --name RH-Lap --ipc --enable-crypto --profile-dir C:/Users/ADMIN/AppData/Local --prevent-sleep --log C:/Users/ADMIN/deskflow.log --address :24800 -c C:/Users/ADMIN/AppData/Local/Deskflow/deskflow-server.conf --tls-cert C:/Users/ADMIN/AppData/Local/Deskflow/tls/deskflow.pem
[2025-02-08T16:36:06] INFO: service status: active
[2025-02-08T16:36:06] DEBUG: start ipc handle data
[2025-02-08T16:36:06] DEBUG: ipc read: ICMD
[2025-02-08T16:36:06] DEBUG: finished ipc handle data
[2025-02-08T16:36:06] DEBUG: daemon got new core command
[2025-02-08T16:36:06] INFO: service command updated
[2025-02-08T16:36:07] DEBUG: closing existing process to make way for new one
[2025-02-08T16:36:07] DEBUG: start ipc handle data
[2025-02-08T16:36:07] DEBUG: ipc read: ISDN
[2025-02-08T16:36:07] DEBUG: finished ipc handle data
[2025-02-08T16:36:07] INFO: got ipc shutdown message
[2025-02-08T16:36:07] DEBUG: event queue is ready
[2025-02-08T16:36:07] DEBUG: unregistered hotkey id=1
[2025-02-08T16:36:07] DEBUG: current screen: entered=yes, primary=yes
[2025-02-08T16:36:07] WARNING: current primary screen is not entered on shutdown
[2025-02-08T16:36:07] WARNING: failed to remove the clipboard format listener: 87
[2025-02-08T16:36:07] DEBUG: adopting new buffer
[2025-02-08T16:36:07] DEBUG: discarding 1 event(s)
[2025-02-08T16:36:07] DEBUG: closed display
[2025-02-08T16:36:07] NOTE: stopped server
[2025-02-08T16:36:07] DEBUG: ipc disconnect, closing stream
[2025-02-08T16:36:07] DEBUG: closing socket: E8628E70
[2025-02-08T16:36:07] DEBUG: ipc disconnect, closing stream
[2025-02-08T16:36:07] DEBUG: closing socket: 00000000
[2025-02-08T16:36:07] DEBUG: closing socket: 98F23BB0
[2025-02-08T16:36:07] DEBUG: ipc client disconnected
[2025-02-08T16:36:07] DEBUG: closing socket: 00000000
[2025-02-08T16:36:07] DEBUG: ipc client proxy removed, connected=1
press any key to exit...
[2025-02-08T16:36:27] WARNING: shutdown timed out after 20 secs, forcefully terminating
[2025-02-08T16:36:27] DEBUG: starting command as session user
[2025-02-08T16:36:27] FATAL: failed to get active desktop name
[2025-02-08T16:36:27] DEBUG: getting elevated token, elevation required
[2025-02-08T16:36:27] DEBUG: found winlogon.exe in session 1
[2025-02-08T16:36:27] DEBUG: got token 900, duplicating
[2025-02-08T16:36:27] DEBUG: duplicated, new token: 904
[2025-02-08T16:36:27] INFO: starting new process
[2025-02-08T16:36:27] DEBUG: opening configuration "C:/Users/ADMIN/AppData/Local/Deskflow/deskflow-server.conf"
[2025-02-08T16:36:27] DEBUG: configuration read successfully
[2025-02-08T16:36:27] DEBUG: screen shape: 0,0 5760x2160 (multi-monitor)
[2025-02-08T16:36:27] DEBUG: window is 0x000201e2
[2025-02-08T16:36:27] DEBUG: unable to use desktop as file drag-drop target, code=2
[2025-02-08T16:36:27] DEBUG: adopting new buffer
[2025-02-08T16:36:27] DEBUG: opened display
[2025-02-08T16:36:27] DEBUG: active sides: 2
[2025-02-08T16:36:27] DEBUG: active sides: 2
[2025-02-08T16:36:27] DEBUG: desk Default window is 0x000509ac
[2025-02-08T16:36:27] DEBUG: switched to desk "Default"
[2025-02-08T16:36:27] DEBUG: desktop is now accessible
[2025-02-08T16:36:27] DEBUG: registered hotkey ScrollLock (id=ef14 mask=0000) as id=1
[2025-02-08T16:36:27] NOTE: started server, waiting for clients
[2025-02-08T16:36:27] DEBUG: opening new socket: 25B1A5A0
[2025-02-08T16:36:27] DEBUG: opening new socket: 98F24060
[2025-02-08T16:36:27] DEBUG: event queue is ready
[2025-02-08T16:36:27] DEBUG: accepted ipc client connection
[2025-02-08T16:36:27] DEBUG: add pending events to buffer
[2025-02-08T16:36:27] DEBUG: screen "RH-Lap" shape changed
[2025-02-08T16:36:27] DEBUG: start ipc handle data
[2025-02-08T16:36:27] DEBUG: ipc read: IHEL
[2025-02-08T16:36:27] DEBUG: finished ipc handle data
[2025-02-08T16:36:27] DEBUG: ipc hello, type=node
[2025-02-08T16:36:27] INFO: service status: active
[2025-02-08T16:36:28] DEBUG: started core process from daemon
[2025-02-08T16:37:36] DEBUG: desk Winlogon window is 0x000300c4
[2025-02-08T16:37:36] DEBUG: switched to desk "Winlogon"
[2025-02-08T16:37:38] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:38] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:38] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:39] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:39] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:39] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:39] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:39] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:40] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:41] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:41] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:42] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:42] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:42] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:44] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:44] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:45] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:46] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:47] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:47] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:47] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:48] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:48] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:49] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:49] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:49] WARNING: failed to determine current keyboard layout
[2025-02-08T16:37:49] DEBUG: switched to desk "Default"
[2025-02-08T16:38:26] DEBUG: clipboard update: sequence number 10, current 0
```

**Comment by sithlord48** [comment]
can you give this a go with 1.19.0.155 there has been a bit of update for windows since the last you have tried.

**Comment by Slient1802** [comment]
It seem that in Deskflow: 1.20.0.18 (029cb8fc),Qt: 6.8.2, System: Windows 11 Version 23H2. 
`WARNING: failed to determine current keyboard layout` problems has been fixed.

**Comment by Slient1802** [comment]
It seem that in Deskflow: 1.21.2.5 (cd7d53d2), Qt: 6.9.0, System: Windows 11 Version 23H2
the bug `WARNING: failed to determine current keyboard layout` reappear again
```
2025-04-10T22:38:31] DEBUG1: hook: 0x61200020 0x00390001
[2025-04-10T22:38:31] DEBUG1: hook: 0x07200020 0x00390001
[2025-04-10T22:38:31] DEBUG1: event: Key char=32, vk=0x20, nagr=0, lParam=0x00390001
[2025-04-10T22:38:31] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:31] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:31] WARNING: failed to determine current keyboard layout
[2025-04-10T22:38:31] DEBUG1: onKeyDown id=32 mask=0x0000 button=0x0039 lang=
[2025-04-10T22:38:31] DEBUG1: send key down to "Ruan-Slients-PC" id=32, mask=0x0000, button=0x0039, language=
[2025-04-10T22:38:31] DEBUG1: hook: 0x00000020 0x80390001
[2025-04-10T22:38:31] DEBUG1: hook: 0x61200020 0x80390001
[2025-04-10T22:38:31] DEBUG1: hook: 0x07200020 0x80390001
[2025-04-10T22:38:31] DEBUG1: event: Key char=32, vk=0x20, nagr=0, lParam=0x80390001
[2025-04-10T22:38:31] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:31] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:31] DEBUG1: onKeyUp id=32 mask=0x0000 button=0x0039
[2025-04-10T22:38:31] DEBUG1: send key up to "Ruan-Slients-PC" id=32, mask=0x0000, button=0x0039
[2025-04-10T22:38:31] DEBUG1: hook: 0x00000041 0x001e0001
[2025-04-10T22:38:31] DEBUG1: hook: 0x61410061 0x001e0001
[2025-04-10T22:38:31] DEBUG1: hook: 0x07410061 0x001e0001
[2025-04-10T22:38:31] DEBUG1: event: Key char=97, vk=0x41, nagr=0, lParam=0x001e0001
[2025-04-10T22:38:31] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:31] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:31] WARNING: failed to determine current keyboard layout
[2025-04-10T22:38:31] DEBUG1: onKeyDown id=97 mask=0x0000 button=0x001e lang=
[2025-04-10T22:38:31] DEBUG1: send key down to "Ruan-Slients-PC" id=97, mask=0x0000, button=0x001e, language=
[2025-04-10T22:38:31] DEBUG1: hook: 0x00000041 0x801e0001
[2025-04-10T22:38:31] DEBUG1: hook: 0x61410061 0x801e0001
[2025-04-10T22:38:31] DEBUG1: hook: 0x07410061 0x801e0001
[2025-04-10T22:38:31] DEBUG1: event: Key char=97, vk=0x41, nagr=0, lParam=0x801e0001
[2025-04-10T22:38:31] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:31] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:31] DEBUG1: onKeyUp id=97 mask=0x0000 button=0x001e
[2025-04-10T22:38:31] DEBUG1: send key up to "Ruan-Slients-PC" id=97, mask=0x0000, button=0x001e
[2025-04-10T22:38:31] DEBUG1: hook: 0x00000053 0x001f0001
[2025-04-10T22:38:31] DEBUG1: hook: 0x61530073 0x001f0001
[2025-04-10T22:38:31] DEBUG1: hook: 0x07530073 0x001f0001
[2025-04-10T22:38:31] DEBUG1: event: Key char=115, vk=0x53, nagr=0, lParam=0x001f0001
[2025-04-10T22:38:31] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:31] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:31] WARNING: failed to determine current keyboard layout
[2025-04-10T22:38:31] DEBUG1: onKeyDown id=115 mask=0x0000 button=0x001f lang=
[2025-04-10T22:38:31] DEBUG1: send key down to "Ruan-Slients-PC" id=115, mask=0x0000, button=0x001f, language=
[2025-04-10T22:38:32] DEBUG1: hook: 0x00000053 0x801f0001
[2025-04-10T22:38:32] DEBUG1: hook: 0x61530073 0x801f0001
[2025-04-10T22:38:32] DEBUG1: hook: 0x07530073 0x801f0001
[2025-04-10T22:38:32] DEBUG1: event: Key char=115, vk=0x53, nagr=0, lParam=0x801f0001
[2025-04-10T22:38:32] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:32] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:32] DEBUG1: onKeyUp id=115 mask=0x0000 button=0x001f
[2025-04-10T22:38:32] DEBUG1: send key up to "Ruan-Slients-PC" id=115, mask=0x0000, button=0x001f
[2025-04-10T22:38:37] DEBUG: setting service status: state=4, step=0, waitHint=0
[2025-04-10T22:38:41] DEBUG1: hook: 0x00000020 0x00390001
[2025-04-10T22:38:41] DEBUG1: hook: 0x61200020 0x00390001
[2025-04-10T22:38:41] DEBUG1: hook: 0x07200020 0x00390001
[2025-04-10T22:38:41] DEBUG1: event: Key char=32, vk=0x20, nagr=0, lParam=0x00390001
[2025-04-10T22:38:41] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:41] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:41] WARNING: failed to determine current keyboard layout
[2025-04-10T22:38:41] DEBUG1: onKeyDown id=32 mask=0x0000 button=0x0039 lang=
[2025-04-10T22:38:41] DEBUG1: send key down to "Ruan-Slients-PC" id=32, mask=0x0000, button=0x0039, language=
[2025-04-10T22:38:41] DEBUG1: hook: 0x00000020 0x80390001
[2025-04-10T22:38:41] DEBUG1: hook: 0x61200020 0x80390001
[2025-04-10T22:38:41] DEBUG1: hook: 0x07200020 0x80390001
[2025-04-10T22:38:41] DEBUG1: event: Key char=32, vk=0x20, nagr=0, lParam=0x80390001
[2025-04-10T22:38:41] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:41] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:41] DEBUG1: onKeyUp id=32 mask=0x0000 button=0x0039
[2025-04-10T22:38:41] DEBUG1: send key up to "Ruan-Slients-PC" id=32, mask=0x0000, button=0x0039
[2025-04-10T22:38:42] DEBUG1: hook: 0x00000041 0x001e0001
[2025-04-10T22:38:42] DEBUG1: hook: 0x61410061 0x001e0001
[2025-04-10T22:38:42] DEBUG1: hook: 0x07410061 0x001e0001
[2025-04-10T22:38:42] DEBUG1: event: Key char=97, vk=0x41, nagr=0, lParam=0x001e0001
[2025-04-10T22:38:42] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:42] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:42] WARNING: failed to determine current keyboard layout
[2025-04-10T22:38:42] DEBUG1: onKeyDown id=97 mask=0x0000 button=0x001e lang=
[2025-04-10T22:38:42] DEBUG1: send key down to "Ruan-Slients-PC" id=97, mask=0x0000, button=0x001e, language=
[2025-04-10T22:38:43] DEBUG1: hook: 0x00000041 0x801e0001
[2025-04-10T22:38:43] DEBUG1: hook: 0x61410061 0x801e0001
[2025-04-10T22:38:43] DEBUG1: hook: 0x07410061 0x801e0001
[2025-04-10T22:38:43] DEBUG1: event: Key char=97, vk=0x41, nagr=0, lParam=0x801e0001
[2025-04-10T22:38:43] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:43] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:43] DEBUG1: onKeyUp id=97 mask=0x0000 button=0x001e
[2025-04-10T22:38:43] DEBUG1: send key up to "Ruan-Slients-PC" id=97, mask=0x0000, button=0x001e
[2025-04-10T22:38:43] DEBUG1: hook: 0x00000053 0x001f0001
[2025-04-10T22:38:43] DEBUG1: hook: 0x61530073 0x001f0001
[2025-04-10T22:38:43] DEBUG1: hook: 0x07530073 0x001f0001
[2025-04-10T22:38:43] DEBUG1: event: Key char=115, vk=0x53, nagr=0, lParam=0x001f0001
[2025-04-10T22:38:43] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:43] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:43] WARNING: failed to determine current keyboard layout
[2025-04-10T22:38:43] DEBUG1: onKeyDown id=115 mask=0x0000 button=0x001f lang=
[2025-04-10T22:38:43] DEBUG1: send key down to "Ruan-Slients-PC" id=115, mask=0x0000, button=0x001f, language=
[2025-04-10T22:38:43] DEBUG1: hook: 0x00000053 0x801f0001
[2025-04-10T22:38:43] DEBUG1: hook: 0x61530073 0x801f0001
[2025-04-10T22:38:43] DEBUG1: hook: 0x07530073 0x801f0001
[2025-04-10T22:38:43] DEBUG1: event: Key char=115, vk=0x53, nagr=0, lParam=0x801f0001
[2025-04-10T22:38:43] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:43] DEBUG1: new mask: 0x0000
[2025-04-10T22:38:43] DEBUG1: onKeyUp id=115 mask=0x0000 button=0x001f
[2025-04-10T22:38:43] DEBUG1: send key up to "Ruan-Slients-PC" id=115, mask=0x0000, button=0x001f
[2025-04-10T22:38:48] DEBUG: setting service status: state=4, step=0, waitHint=0
```

**Comment by ksajan** [comment]
I am also experiencing the same bug with `failed to deremeine current keyboard layout`. Is there a way to mitigate this issue from our settings or its needs to be fixed in the package itself.

**Comment by RSlient007** [comment]
My temporary solution when facing the bug `WARNING: failed to determine current keyboard layout` was to manually reset the connection Deskflow on both sides (Client & Server)

**Comment by RSlient007** [comment]
Update Deskflow: 1.22.0.102 (42cd01ef), Qt: 6.8.3, System: Windows 11 Version 23H2 bug `WARNING: failed to determine current keyboard layout` still appears
```
[2025-07-04T13:15:57] WARNING: failed to determine current keyboard layout
[2025-07-04T13:15:57] DEBUG1: onKeyDown id=57 mask=0x2000 button=0x000a lang=
[2025-07-04T13:15:57] DEBUG1: hook: 0x00000039 0x800a0001
[2025-07-04T13:15:57] DEBUG1: hook: 0x61390039 0x800a0001
[2025-07-04T13:15:57] DEBUG1: hook: 0x07390039 0x800a0001
[2025-07-04T13:15:57] DEBUG1: event: Key char=57, vk=0x39, nagr=0, lParam=0x800a0001
[2025-07-04T13:15:57] DEBUG1: new mask: 0x2000
[2025-07-04T13:15:57] DEBUG1: new mask: 0x2000
[2025-07-04T13:15:57] DEBUG1: onKeyUp id=57 mask=0x2000 button=0x000a
[2025-07-04T13:15:58] DEBUG1: hook: 0x00000037 0x00080001
[2025-07-04T13:15:58] DEBUG1: hook: 0x61370037 0x00080001
[2025-07-04T13:15:58] DEBUG1: hook: 0x07370037 0x00080001
[2025-07-04T13:15:58] DEBUG1: event: Key char=55, vk=0x37, nagr=0, lParam=0x00080001
[2025-07-04T13:15:58] DEBUG1: new mask: 0x2000
[2025-07-04T13:15:58] DEBUG1: new mask: 0x2000
[2025-07-04T13:15:58] WARNING: failed to determine current keyboard layout
[2025-07-04T13:15:58] DEBUG1: onKeyDown id=55 mask=0x2000 button=0x0008 lang=
[2025-07-04T13:15:58] DEBUG1: hook: 0x00000037 0x80080001
[2025-07-04T13:15:58] DEBUG1: hook: 0x61370037 0x80080001
[2025-07-04T13:15:58] DEBUG1: hook: 0x07370037 0x80080001
[2025-07-04T13:15:58] DEBUG1: event: Key char=55, vk=0x37, nagr=0, lParam=0x80080001
[2025-07-04T13:15:58] DEBUG1: new mask: 0x2000
[2025-07-04T13:15:58] DEBUG1: new mask: 0x2000
[2025-07-04T13:15:58] DEBUG1: onKeyUp id=55 mask=0x2000 button=0x0008
[2025-07-04T13:15:58] DEBUG1: hook: 0x00000030 0x000b0001
[2025-07-04T13:15:58] DEBUG1: hook: 0x61300030 0x000b0001
[2025-07-04T13:15:58] DEBUG1: hook: 0x07300030 0x000b0001
[2025-07-04T13:15:58] DEBUG1: event: Key char=48, vk=0x30, nagr=0, lParam=0x000b0001
[2025-07-04T13:15:58] DEBUG1: new mask: 0x2000
[2025-07-04T13:15:58] DEBUG1: new mask: 0x2000
[2025-07-04T13:15:58] WARNING: failed to determine current keyboard layout
[2025-07-04T13:15:58] DEBUG1: onKeyDown id=48 mask=0x2000 button=0x000b lang=
[2025-07-04T13:15:59] DEBUG1: hook: 0x00000030 0x800b0001
[2025-07-04T13:15:59] DEBUG1: hook: 0x61300030 0x800b0001
[2025-07-04T13:15:59] DEBUG1: hook: 0x07300030 0x800b0001
[2025-07-04T13:15:59] DEBUG1: event: Key char=48, vk=0x30, nagr=0, lParam=0x800b0001
[2025-07-04T13:15:59] DEBUG1: new mask: 0x2000
[2025-07-04T13:15:59] DEBUG1: new mask: 0x2000
[2025-07-04T13:15:59] DEBUG1: onKeyUp id=48 mask=0x2000 button=0x000b
[2025-07-04T13:15:59] DEBUG1: hook: 0x00000034 0x00050001
[2025-07-04T13:15:59] DEBUG1: hook: 0x61340034 0x00050001
[2025-07-04T13:15:59] DEBUG1: hook: 0x07340034 0x00050001
[2025-07-04T13:15:59] DEBUG1: event: Key char=52, vk=0x34, nagr=0, lParam=0x00050001
[2025-07-04T13:15:59] DEBUG1: new mask: 0x2000
[2025-07-04T13:15:59] DEBUG1: new mask: 0x2000
[2025-07-04T13:15:59] WARNING: failed to determine current keyboard layout
[2025-07-04T13:15:59] DEBUG1: onKeyDown id=52 mask=0x2000 button=0x0005 lang=
[2025-07-04T13:15:59] DEBUG1: hook: 0x00000034 0x80050001
[2025-07-04T13:15:59] DEBUG1: hook: 0x61340034 0x80050001
[2025-07-04T13:15:59] DEBUG1: hook: 0x07340034 0x80050001
[2025-07-04T13:15:59] DEBUG1: event: Key char=52, vk=0x34, nagr=0, lParam=0x80050001
[2025-07-04T13:15:59] DEBUG1: new mask: 0x2000
[2025-07-04T13:15:59] DEBUG1: new mask: 0x2000
[2025-07-04T13:15:59] DEBUG1: onKeyUp id=52 mask=0x2000 button=0x0005
[2025-07-04T13:15:59] DEBUG: switched to desk "Default"
```

**Comment by RSlient007** [comment]
I can't reproduce the problem. I assume the bug has been fixed in Deskflow: 1.24.0.0 (56a1bd68)
Qt: 6.9.0
System: Windows 11 Version 23H2
I will close this issue for now
