### ISSUE TITLE
Everything typed on client is in ALL CAPS (Wayland)

### ISSUE THREAD

**Issue by jwakely** [deskflow/deskflow#7886]
💵 **Bounty**: $200 ([details](https://github.com/deskflow/deskflow/issues/7886#issuecomment-2593078642))

### Project

Deskflow

### Deskflow version number

1.17.1

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [ ] Linux (X11)
- [X] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [X] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [X] I am not using macOS

### Continuous build

- [X] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

Fedora 40, running KDE/plasma desktop on Wayland. Using Fedora 40 RPMs downloaded from github.com/deskflow/deskflow.
UK keyboard, KDE region settings are for UK.

### Deskflow configuration

Two Fedora 40 systems. The deskflow server is a laptop with an external display attached (so two screens for the server). The client is a tower with a single display attached. Connecting over a direct cat-5 cable between the two machines, with manually assigned IP addresses.

### What steps will reproduce the problem?

Start Deskflow on both systems, click "Allow" in "Input capture requested" and "Remote control requested" dialogs. Move mouse from server to client and type using the server's keyboard. All letters typed are uppercase. Holding Shift doesn't change anything. Turning caps lock on doesn't change it.

Other characters are wrong too:
Typing `[` enters `8` on the client, `]` enters `9`, backslash enters `-` and `|` enters `¬`

This doesn't always happen. After rebooting both systems and restarting deskflow it seems to be OK again for a while. Once it starts happening, no amount of restarting deskflow on server and client helps, nor does logging out of KDE on the client and logging in again and restarting deskflow.

Anything typed directly on the keyboard connected to the server works as normal, only characters typed on the server's keyboard and shared with the client via deskflow are incorrect.

### Log output

```shell
Server logs:

[2024-11-12T14:19:21] INFO: starting core server process (desktop mode)
[2024-11-12T14:19:21] INFO: core config file: /home/jwakely/.config/Deskflow/deskflow-server.conf
[2024-11-12T14:19:21] INFO: running command: /usr/bin/deskflow-server -f --no-tray --debug INFO --name carbon.home --enable-crypto --address :24800 -c /home/jwakely/.config/Deskflow/deskflow-server.conf --tls-cert /home/jwakely/.config/Deskflow/tls/deskflow.pem
[2024-11-12T14:19:21] INFO: using ei screen for wayland
[2024-11-12T14:19:21] NOTE: started server, waiting for clients
[2024-11-12T14:19:21] INFO: accepted secure socket
[2024-11-12T14:19:21] INFO: network encryption protocol: TLSv1.3
[2024-11-12T14:19:21] NOTE: accepted client connection
[2024-11-12T14:19:21] INFO: local languages: en
[2024-11-12T14:19:21] NOTE: client "wraith.home" has connected
[2024-11-12T14:19:21] INFO: version check server success, http status: 200
[2024-11-12T14:19:26] NOTE: logical output size: 2560x2520@0.0
[2024-11-12T14:19:26] NOTE: logical output size: 2560x2520@0.0
[2024-11-12T14:19:26] NOTE: failed to create xkb context: Resource temporarily unavailable
[2024-11-12T14:19:26] NOTE: logical output size: 2560x2520@0.0
[2024-11-12T14:19:26] WARNING: failed to apply barrier 1 (640/1440-2559/1440)
[2024-11-12T14:19:26] WARNING: failed to apply barrier 8 (0/1440-2559/1440)
[2024-11-12T14:19:27] INFO: switch from "carbon.home" to "wraith.home" at 30,349
[2024-11-12T14:19:27] INFO: leaving screen
[2024-11-12T14:19:30] WARNING: language "" is unknown
[2024-11-12T14:19:30] WARNING: failed to convert layout lang code: ""
[2024-11-12T14:19:30] WARNING: language "" is unknown
[2024-11-12T14:19:30] WARNING: failed to convert layout lang code: ""
[2024-11-12T14:19:30] WARNING: language "" is unknown
[2024-11-12T14:19:30] WARNING: failed to convert layout lang code: ""
[2024-11-12T14:19:30] WARNING: language "" is unknown
[2024-11-12T14:19:30] WARNING: failed to convert layout lang code: ""
[2024-11-12T14:19:30] WARNING: language "" is unknown
[2024-11-12T14:19:30] WARNING: failed to convert layout lang code: ""
[2024-11-12T14:19:30] WARNING: language "" is unknown
[2024-11-12T14:19:30] WARNING: failed to convert layout lang code: ""
[2024-11-12T14:19:30] WARNING: language "" is unknown
[2024-11-12T14:19:30] WARNING: failed to convert layout lang code: ""
[2024-11-12T14:19:32] INFO: switch from "wraith.home" to "carbon.home" at 2534,2518
[2024-11-12T14:19:32] INFO: entering screen

Client logs:

[2024-11-12T14:21:55] INFO: starting core client process (desktop mode)
[2024-11-12T14:21:55] INFO: running command: /usr/bin/deskflow-client -f --no-tray --debug INFO --name wraith.home --enable-crypto --sync-language 192.168.99.2:24800
[2024-11-12T14:21:55] INFO: using ei screen for wayland
[2024-11-12T14:21:55] NOTE: started client
[2024-11-12T14:21:55] NOTE: connecting to '192.168.99.2': 192.168.99.2:24800
[2024-11-12T14:21:55] NOTE: server fingerprint: 55:B6:30:DF:67:E4:77:47:BD:23:DF:91:B0:3D:3C:E0:A8:D2:E5:54:69:6E:07:6B:C5:03:00:D4:5E:BE:0C:1A
[2024-11-12T14:21:55] INFO: connected to secure socket
[2024-11-12T14:21:55] INFO: server tls certificate info: /CN=Deskflow
[2024-11-12T14:21:55] INFO: network encryption protocol: TLSv1.3
[2024-11-12T14:21:55] INFO: local languages: en
[2024-11-12T14:21:55] INFO: remote languages: en
[2024-11-12T14:21:55] NOTE: connected to server
[2024-11-12T14:21:55] INFO: version check server success, http status: 200
[2024-11-12T14:21:58] NOTE: logical output size: 1920x1080@0.0
[2024-11-12T14:21:58] NOTE: logical output size: 1920x1080@0.0
[2024-11-12T14:21:58] NOTE: failed to create xkb context: Resource temporarily unavailable
[2024-11-12T14:21:58] NOTE: logical output size: 1920x1080@0.0
[2024-11-12T14:22:09] INFO: entering screen
[2024-11-12T14:22:09] INFO: clipboard was updated
[2024-11-12T14:22:09] INFO: clipboard was updated
[2024-11-12T14:22:09] INFO: leaving screen
[2024-11-12T14:22:10] INFO: entering screen
[2024-11-12T14:22:12] INFO: leaving screen
[2024-11-12T14:22:32] INFO: entering screen
[2024-11-12T14:22:54] INFO: leaving screen
[2024-11-12T14:23:57] INFO: entering screen
[2024-11-12T14:24:31] INFO: leaving screen
[2024-11-12T14:24:51] INFO: entering screen
[2024-11-12T14:25:05] INFO: leaving screen
[2024-11-12T14:26:45] INFO: entering screen
[2024-11-12T14:27:08] INFO: leaving screen
[2024-11-12T14:27:32] INFO: entering screen
[2024-11-12T14:28:02] INFO: stopping core process (desktop mode)
[2024-11-12T14:28:02] INFO: stopping core desktop process
[2024-11-12T14:28:02] WARNING: desktop process exited with error code: 9
[2024-11-12T14:28:02] INFO: starting core client process (desktop mode)
[2024-11-12T14:28:02] INFO: running command: /usr/bin/deskflow-client -f --no-tray --debug INFO --name wraith.home --enable-crypto 192.168.99.2:24800
[2024-11-12T14:28:02] INFO: using ei screen for wayland
[2024-11-12T14:28:02] NOTE: started client
[2024-11-12T14:28:02] NOTE: connecting to '192.168.99.2': 192.168.99.2:24800
[2024-11-12T14:28:02] NOTE: server fingerprint: 55:B6:30:DF:67:E4:77:47:BD:23:DF:91:B0:3D:3C:E0:A8:D2:E5:54:69:6E:07:6B:C5:03:00:D4:5E:BE:0C:1A
[2024-11-12T14:28:02] INFO: connected to secure socket
[2024-11-12T14:28:02] INFO: server tls certificate info: /CN=Deskflow
[2024-11-12T14:28:02] INFO: network encryption protocol: TLSv1.3
[2024-11-12T14:28:02] INFO: local languages: en
[2024-11-12T14:28:02] INFO: remote languages: en
[2024-11-12T14:28:02] NOTE: connected to server
[2024-11-12T14:28:04] INFO: entering screen
[2024-11-12T14:28:04] INFO: clipboard was updated
[2024-11-12T14:28:04] INFO: clipboard was updated
[2024-11-12T14:28:05] INFO: leaving screen
[2024-11-12T14:28:05] INFO: entering screen
[2024-11-12T14:28:05] INFO: leaving screen
[2024-11-12T14:28:08] NOTE: logical output size: 1920x1080@0.0
[2024-11-12T14:28:08] NOTE: logical output size: 1920x1080@0.0
[2024-11-12T14:28:08] NOTE: failed to create xkb context: Resource temporarily unavailable
[2024-11-12T14:28:08] NOTE: logical output size: 1920x1080@0.0
[2024-11-12T14:28:09] INFO: entering screen
[2024-11-12T14:28:16] INFO: leaving screen
[2024-11-12T14:28:17] INFO: entering screen
[2024-11-12T14:28:40] INFO: stopping core process (desktop mode)
[2024-11-12T14:28:40] INFO: stopping core desktop process
[2024-11-12T14:28:40] WARNING: desktop process exited with error code: 9
[2024-11-12T14:28:40] INFO: starting core client process (desktop mode)
[2024-11-12T14:28:40] INFO: running command: /usr/bin/deskflow-client -f --no-tray --debug INFO --name wraith.home --enable-crypto --sync-language 192.168.99.2:24800
[2024-11-12T14:28:40] INFO: using ei screen for wayland
[2024-11-12T14:28:40] NOTE: started client
[2024-11-12T14:28:40] NOTE: connecting to '192.168.99.2': 192.168.99.2:24800
[2024-11-12T14:28:40] NOTE: server fingerprint: 55:B6:30:DF:67:E4:77:47:BD:23:DF:91:B0:3D:3C:E0:A8:D2:E5:54:69:6E:07:6B:C5:03:00:D4:5E:BE:0C:1A
[2024-11-12T14:28:40] INFO: connected to secure socket
[2024-11-12T14:28:40] INFO: server tls certificate info: /CN=Deskflow
[2024-11-12T14:28:40] INFO: network encryption protocol: TLSv1.3
[2024-11-12T14:28:40] INFO: local languages: en
[2024-11-12T14:28:40] INFO: remote languages: en
[2024-11-12T14:28:40] NOTE: connected to server
[2024-11-12T14:28:44] NOTE: logical output size: 1920x1080@0.0
[2024-11-12T14:28:44] NOTE: logical output size: 1920x1080@0.0
[2024-11-12T14:28:44] NOTE: failed to create xkb context: Resource temporarily unavailable
[2024-11-12T14:28:44] NOTE: logical output size: 1920x1080@0.0
[2024-11-12T14:28:45] INFO: entering screen
[2024-11-12T14:28:45] INFO: clipboard was updated
[2024-11-12T14:28:45] INFO: clipboard was updated
[2024-11-12T14:28:48] INFO: leaving screen
[2024-11-12T14:28:49] INFO: entering screen
[2024-11-12T14:28:49] INFO: leaving screen
[2024-11-12T14:29:14] INFO: entering screen
[2024-11-12T14:29:26] INFO: leaving screen
[2024-11-12T14:29:26] INFO: entering screen
```

**Comment by sithlord48** [comment]
your caps lock or fn or something is out of sync between the two this can happen if they start at a different state. 
on the client toggle FN OR capslock. Then go back to the server and do it again they should be in sync now..

**Comment by jwakely** [comment]
Yeah I tried that obviously. It's not the problem. I never use caps lock, and it's definitely OFF on both machines all the time. Toggling it on and off on both machines doesn't change it.

I've just rebooted the client (but left the server up with deskflow running) and after logging back in and restarting deskflow on the client, the problem is gone. But it will return. Next time it happens, I'll check again that it's not caps lock on either machine.

**Comment by sithlord48** [comment]
from what you described it sounds like FN lock is on

**Comment by jwakely** [comment]
It does seem like that, but I don't have a numlock key on any of my keyboards, the laptop doesn't have a number pad (ThinkPad Carbon P1), and neither do either of the keyboards attached to the two machines (both "tenkeyless" 80% keyboards).

The laptop running the deskflow server does have a FnLock but it's never on (there's a LED so I'd notice). Toggling it doesn't change the odd behaviour on the client.

I never had this problem with Synergy on X11, it's only with deskflow on Wayland (although I've also upgraded from Fedora 39 to Fedora 40 in that time, so several things have changed, and I can't revert to X11 to test if it still happens with synergy on Fedora 40).

I've just rebooted the client machine and started Deskflow, and noticed that sending `[` and `]` from the server machine's keyboard _always_ types `8` and `9`, even after just rebooting. Whereas the ALL CAPS behaviour doesn't happen on reboot, only later.

**Comment by jwakely** [comment]
After some more experimenting ...

Immediately after booting up and starting deskflow, the `[` and `]` keys are sent incorrectly. Alphabetical characters are sent correctly. I guess I just never noticed the `[` and `]` issue until today when I started looking into this in more detail.

If I then quit deskflow on the client, then ensure that none of caps lock, fn lock, and num lock (which doesn't even exist) are ON, then restart deskflow on the client ... then typing any lowercase alpha keys on the server sends UPPERCASE to the client. There seems to be no way to fix that, except rebooting (and then it's OK until the next time I restart deskflow on the client).

**Comment by nbolton** [comment]
IIRC, caps lock can control the full duplex or half duplex mode. I wonder if that could be something to do with it. Could you share your server config file?

**Comment by jwakely** [comment]
This is the output of `File->Save configuration as...`

```
section: screens
        carbon.home:
                halfDuplexCapsLock = false
                halfDuplexNumLock = false
                halfDuplexScrollLock = false
                xtestIsXineramaUnaware = false
                switchCorners = none
                switchCornerSize = 0
        wraith.home:
                halfDuplexCapsLock = false
                halfDuplexNumLock = false
                halfDuplexScrollLock = false
                xtestIsXineramaUnaware = false
                switchCorners = none
                switchCornerSize = 0
end

section: aliases
end

section: links
        carbon.home:
                right = wraith.home
        wraith.home:
                left = carbon.home
end

section: options
        protocol = barrier
        relativeMouseMoves = false
        win32KeepForeground = false
        disableLockToScreen = false
        clipboardSharing = true
        clipboardSharingSize = 3072
        switchCorners = none
        switchCornerSize = 0
end
```

**Comment by jwakely** [comment]
Wow, I don't think I ever realised that I can double-click on the computer name on the "Computers" tab of the "Server Configuration" dialog, and change settings for each computer. I thought it was just for dragging around the relative positions, ha!

Anyway, now that I know where to change those settings, I've tried various combinations of the check boxes for "CAPS LOCK key" and "NUM LOCK key" on the client and the server, with no effect.

**Comment by jwakely** [comment]
I also did "Help->Clear settings" and re-configured everything on the server, but after reconnecting the client the problem is still present.

So then I did the same on the client, and reconnected, and the problem is still present.

**Comment by jwakely** [comment]
I also unchecked "Use server's keyboard language on this computer" in the client preferences, no change.

**Comment by jwakely** [comment]
Aha! Fixed it.... temporarily.

On the client I changed the KDE keyboard model from "Generic | Generic 102-key PC" to "Generic | Generic 86-key PC" and hit Apply, and after that the keys typed on the server were not all uppercase. But the <kbd>[</kbd> and <kbd>]</kbd> keys on the server still type `8` and `9` on the client.

However, restarting Deskflow on the client made the problem come back after reconnecting to the server. Changing the client's keyboard layout again fixes it (for alphabetical keys), at least until Deskflow is restarted.

It doesn't seem to matter which keyboard layout I change to, it's just the act of changing the layout which (temporarily) fixes the alphabetical keys.

I haven't found a way to fix <kbd>[</kbd>, <kbd>]</kbd>, and <kbd>\\</kbd>

**Comment by nbolton** [comment]
Glad you found a partial workaround. Thanks for sharing.

**Comment by Cris70** [comment]
Hi,
I am experiencing the exact same problem with two openSuse Tumbleweed PCs.

**Comment by BarryBanana** [comment]
Same problem with two Thinkpads running Fedora 41 Workstation Plasma 6.x

**Comment by nbolton** [comment]
I am also seeing this on my Arch client running KDE. 

I guess it's a KDE/KWin specific issue?

**Comment by sithlord48** [comment]
I don't see this issue using KDE myself so not sure its an upstream issue. I suspect its more like the numlock issues where caps is out of sync between the two

**Comment by nbolton** [comment]
> > I am also seeing this on my Arch client running KDE. I guess it's a KDE/KWin specific issue?
> 
> Do you also have [ and ] keys sending the wrong thing? Or is that a separate issue from the ALL CAPS problem?

Hmm yeah on my KDE client, `[` and `]` from the server are received as `8` and `9` without a modifier. With shift, I get `&` and `)`... very odd.

**Comment by sithlord48** [comment]
For whom every takes this up, 
 I suspect this has todo with the language settings as well as maybe a desync on caps or shift being stuck in a "HELD" state.

**Comment by nbolton** [comment]
I wonder if this is relevant: When I fall back to XWayland (`--no-libei` in Synergy v1.17.1) the problem goes away. So, the issue has to be somewhere in between: `libei -> libportal -> xdg-desktop-portal -> wayland-protocols -> kwin`

**Comment by nbolton** [comment]
Possibly fixed by:
- #8121

**Comment by jwakely** [comment]
`[2024-11-12T14:28:44] NOTE: failed to create xkb context: Resource temporarily unavailable`

Should that have been printed with a higher level than NOTE?

**Comment by nbolton** [comment]
> `[2024-11-12T14:28:44] NOTE: failed to create xkb context: Resource temporarily unavailable`
> 
> Should that have been printed with a higher level than NOTE?

Fixed in: #8122

I believe this should be at least a warning.

**Comment by nbolton** [comment]
> Possibly fixed by:
> 
> * [Fix keymap not correctly loading for the Ei backend #8121](https://github.com/deskflow/deskflow/pull/8121)

@jwakely PR merged. Please try latest continuous build to see if this is fixed for you.
https://github.com/deskflow/deskflow/releases

**Comment by jwakely** [comment]
I only have access to one machine right now but I'll test it ASAP (probably at the weekend)

**Comment by mlunax** [comment]
@nbolton I still have the same information "failed to convert layout'.
Not fixed with special chars like "Ł Ó" etc

**Comment by nbolton** [comment]
@jwakely Perhaps we could change the title to talk about non-ASCII chars since the caps issue seems to have been fixed. What do you think?

**Comment by nbolton** [comment]
Bounty paid. Congrats @BMagnu, thanks for your PR which has fixed the all caps issue for me. I decided to award the bounty since I created it initially for the all caps bug which seems to have been fixed now.

**Comment by sithlord48** [comment]
@nbolton  if this one if fixed should it be closed?

**Comment by nbolton** [comment]
I'm going to close this issue since the title is about caps and the other keys were a side note and seems to be a different bug. We should raise a new bug for this:

> > [@nbolton](https://github.com/nbolton) Seems fixed only ASCII chars. I still have the same information "failed to convert layout'. Not fixed with special chars like "Ł Ó" etc
> > Fedora 41 - compiled from today source ArchLinux - loaded from github CD
> 
> > > Other characters are wrong too:
> > > Typing [ enters 8 on the client, ] enters 9, backslash enters - and | enters ¬

@jwakely Would you like to do the honors or shall I?

**Comment by jwakely** [comment]
Sorry for the delay. I can confirm that lowercase alpha chars work now. I created #8168 for the other keys.
