### ISSUE TITLE
Multiple deskflow icons on MacOS

### ISSUE THREAD

**Issue by lesca** [deskflow/deskflow#8050]
Hello,

The running version is 1.18.0.0

On MacOS, server mode, there are **three icons** on the dock!! I quit the app, remove all the icons, and start the app again, there are two icons. Later, if a client connects, it can be three. 

<img width="218" alt="截屏2025-01-06 21 44 22" src="https://github.com/user-attachments/assets/6efd2bb3-f996-4d6f-b098-fffc38ec29dc" />

Is this a bug? How to prevent this? 

Thanks!!

**Comment by sithlord48** [comment]
This should be fixed by #8027  where you can't run more then one instance and 
#https://github.com/deskflow/deskflow/pull/8042 should also get them to act like on app too

**Comment by sithlord48** [comment]
@lesca can you try with the most current Continuous release . I suspect this is now fixed.

**Comment by lesca** [comment]
> @lesca can you try with the most current Continuous release . I suspect this is now fixed.

sorry for the late reply. I will try it today.

**Comment by lesca** [comment]
Hello @sithlord48 
I just installed this [continuous version](https://github.com/deskflow/deskflow/releases/tag/continuous) - [Commit 9501b59](https://github.com/deskflow/deskflow/commit/9501b59f8187ae64883d386aadb7b68094688f4b)

But the app won't open, the message is 
```
"Deskflow.app" is damaged and can't be opened you should move it to the trash.
```

I also tried `brew install --casks deskflow-dev`, but the app still won't open.

**Comment by sithlord48** [comment]
Oh i should fix that part

**Comment by sithlord48** [comment]
@lesca  that should be fixed now you should be able to install from brew and it should work again

**Comment by lesca** [comment]
Hello @sithlord48 , appologies for late response. I can now successfully instal deskflow with `brew install deskflow-dev` and the version is 1.18.0.46 (3875e411)

Two icons appear when the app starts as server mode. Once the client connects, no more icons show up. This is a great improvement. 

<img width="223" alt="截屏2025-01-10 09 04 32" src="https://github.com/user-attachments/assets/f060894f-4fae-4b1f-8135-52b1451c6771" />

**Comment by sithlord48** [comment]
Im typing this with my mac as a server and i only see the one icon. Is it possible you have a pinned copy and that is your duplicate ?  If you remove those entries in the dock plist do the two entries still return ?

**Comment by lesca** [comment]
> Im typing this with my mac as a server and i only see the one icon.

Not sure why, but on my mac m4 air, running Sonoma 14.6.1 (23G93) it has the issue. 
Can you share the caches path? Maybe I need to clean it up because the app loads my old configs directly after it's installed. 

>  Is it possible you have a pinned copy and that is your duplicate ? 

No, that was just recent apps and I did not pin the app.

To be more specific, if I pin the app (figure below), everytime it starts, it adds a new icon in the recent app area:

<img width="270" alt="截屏2025-01-10 10 21 16" src="https://github.com/user-attachments/assets/8fd0f134-005b-4695-9375-cfef242a8401" />


> If you remove those entries in the dock plist do the two entries still return ?

Yes. I did remove all icons from the recent apps area, and next time I open the app, it just adds another icon there.

**Comment by sithlord48** [comment]
the settings files for deskflows are in `~/Library/Deskflow` `~/Library/Preferences/Deskflow` and `~/Libarary/Preferences/org.deskflow.Deskflow.plist`

Im on 15.2 maybe its a 14.x thing?

**Comment by lesca** [comment]
> the settings files for deskflows are in `~/Library/Deskflow` `~/Library/Preferences/Deskflow` and `~/Libarary/Preferences/org.deskflow.Deskflow.plist`

Unfortunately, removing the configs doesn't help. 

> Im on 15.2 maybe its a 14.x thing?

That's a possible point. I will upgrade when I have time and try again.

**Comment by nbolton** [comment]
I think this is because macOS creates an icon for each process, and since we're launching the core (server/client) from the GUI, that's why we get multiple icons. This has been an issue for years, as of something like macOS 10.13-ish.

I think the solution might be to have an option to run the core as a user agent, rather than running it from the GUI. This is something I plan to do anyway (probably soon).

**Comment by sithlord48** [comment]
They are all now under a proper bundle this is why we only see only entry in Accessibility now . To mac os the bundle is the app it should not show two icons. I also can not reproduce this

**Comment by sithlord48** [comment]
Any update on this ? I only ever see one icon on my dock still.

**Comment by lesca** [comment]
Hello @sithlord48 , I've updated to 15.3 and installed the latest dev version, but it's still the same. 

<img width="223" alt="Image" src="https://github.com/user-attachments/assets/bca92a0a-4bc7-4837-ab61-bc6b77d29f51" />

**Comment by sithlord48** [comment]
can you confirm that the two icons are not pinned to your dock ? 
does anyone one else have this problem to eliminate your machines configuration

**Comment by lesca** [comment]
Hello @sithlord48 , they are not pinned. they are in the "recent apps" area. I did not pin the app yet.

**Comment by phillijw** [comment]
I am on macos client v1.23 with windows v1.23 as server. I have the same issue. After some weekends I come back with 20+ icons being displayed. I currently have 3 from the last couple hours and only the very first (left) one does anything. I'm able to right-click and quit the other ones with no ill effects and clicking them does nothing.

**Comment by sithlord48** [comment]
I still can't reproduce this :(

**Comment by trinode** [comment]
Same issue here. 

Installed via homebrew
M4 Pro Macbook Pro running Tahoe 26.04

**Comment by AlbertShown** [comment]
> I still can't reproduce this :(

@sithlord48 Check your Dock settings.

<img width="944" height="78" alt="Image" src="https://github.com/user-attachments/assets/c1c17413-690b-42da-9c39-e13a87edf15d" />

**Comment by phillijw** [comment]
It has not happened for me in a long time

**Comment by trinode** [comment]
just to be clear, @AlbertShown meant that the `show suggested and recent apps in dock` setting needs to be on since this is where the problem is (recent apps list), despite the screenshot of it being turned off.

**Comment by DanielEsc0911** [comment]
I'm also having this issue, i'm on a M4 Macbook Air / macOS Tahoe 26.5.2 (25F84), "add recent and recomended apps to dock" option enabled, deskflow is not pinned to the dock (this does not chenge the behaviour regardless) and deskflow version 1.26.0.0 installed via brew.
```
~ % brew list
==> Formulae
ada-url		cocoapods	libnghttp2	libyaml		nbytes		ruby		uvwasi
brotli		fmt		libnghttp3	llhttp		node		simdjson	xcodegen
c-ares		hdrhistogram_c	libngtcp2	lz4		openssl@3	simdutf		xz
ca-certificates	icu4c@78	libuv		merve		readline	sqlite		zstd

==> Casks
deskflow
```

With deskflow totally closed, opening the app results in two icons appearing one afteher the other (mind is in spanish)

<img width="810" height="721" alt="Image" src="https://github.com/user-attachments/assets/08fe33f1-cda4-43b3-b2c2-2df0234dbeb5" />

Clicking the red X in the window, makes the bottom active dot go away from the app icon (this is expected behaviour) then clicking on either icon open the window again but the bottom active dot only appears on the leftmost app icon regardless on wich one is clicked this logic applies also when the app is pinned to the dock, only the leftmost icon gets the dot going on.

After removing all the icons from the dock with the window closed opening the app again via the app menu or the context menu when right clicking the icon in hte status bar

<img width="478" height="320" alt="Image" src="https://github.com/user-attachments/assets/375f81d8-a54c-4b6c-858a-8e0d60a3eecd" />

I will also take this time to mention the error in translation Abierto Deskflow > Abrir Deskflow, both Abierto and Abrir translate to open but Abrir is the verb while Abierto is an adjective/participle 

TL;DR the issue seems to be that on startup deskflows opens 1 aditional icon entry when the "add recent and recomended apps to dock" option is enabled

**Comment by sithlord48** [comment]
Thanks for the translation check @DanielEsc0911, I've made a [PR](https://github.com/deskflow/deskflow/pull/9966) to fix the translation. Please lmk if you find any more feel free to open an issue w/ a list just be sure to check with the continuous version before you do.

**Comment by VTRiot** [comment]
Still reproducible on 1.26.0. I think I can offer a concrete mechanism that hasn't been mentioned yet, and it may explain why @sithlord48 can't reproduce it while others accumulate icons over days.

**Environment**
- macOS 26.4.1 (25E253), Apple Silicon
- Deskflow 1.26.0.0, installed via Homebrew cask
- Client mode

### The mechanism I believe is at work: orphaned `deskflow-core` processes

@nbolton already identified the root shape back in January 2025 ("macOS creates an icon for each process, and since we're launching the core from the GUI, that's why we get multiple icons"). The part I'd like to add is **why they persist and accumulate**: the core is not reliably torn down with the GUI, and it survives as an orphan.

Measured on my machine just now — the GUI was stopped **gracefully** via `launchctl bootout` of the LaunchAgent that starts it:

```
[before] 94035     1  /Applications/Deskflow.app/Contents/MacOS/Deskflow
         94042 94035  /Applications/Deskflow.app/Contents/MacOS/deskflow-core
[after ] 94042     1  /Applications/Deskflow.app/Contents/MacOS/deskflow-core
```

The core is re-parented to PID 1 and keeps running. Same result with `SIGKILL` on the GUI. So this is **not limited to abnormal termination** — a clean stop leaves an orphan too.

Critically, that orphan still occupies an app slot with the parent bundle's identity. After the GUI is gone, `lsappinfo` still lists:

```
bundleID="org.deskflow.deskflow"
executable path="/Applications/Deskflow.app/Contents/MacOS/deskflow-core"
```

The core has **no Info.plist of its own** — there's no separate bundle, and `otool -s __TEXT __info_plist` on the core binary returns nothing. It therefore inherits `CFBundleName`, `CFBundleIdentifier` and the icon from the parent bundle. From macOS's point of view there is simply a second "Deskflow" app.

So each start/stop cycle can leave one more identically-named, identically-iconed entry behind, and the count grows monotonically until reboot.

### Why this fits the reports here

- @phillijw: *"After some weekends I come back with 20+ icons... only the very first (left) one does anything. I'm able to right-click and quit the other ones with no ill effects."* That is exactly how orphaned cores would behave — inert, harmless to kill, one per past session.
- @lesca seeing 2 and sometimes 3: GUI + live core, plus a leftover orphan from a previous run.
- @sithlord48 unable to reproduce: if you start the app, look at the Dock, and quit — within a single session there's nothing to accumulate yet. The symptom needs *repeated* start/stop cycles (or crashes/logouts) before the count becomes visible.

To check for leftovers on a machine that shows the problem:

```sh
ps -eo pid,ppid,args | grep '[d]eskflow-core'
```

Any line with `ppid` of `1` is an orphan from an earlier session.

### Relationship to other issues

This looks like the same underlying defect as #8879 ("core process stays running when GUI is killed", closed) and is adjacent to #9903 (core hanging on quit). If the core outliving the GUI is fixed, I'd expect the icon accumulation here to largely go away — the remaining "two entries while running" would just be the GUI + its live core, which is the architectural point @nbolton raised.

### Note on the "recent apps" Dock setting

Turning off *"Show suggested and recent apps in Dock"* does hide the extra entries, but I don't think it addresses the cause — the orphaned processes are still resident, still holding the app's identity, and still accumulating. It changes visibility, not state.

### Suggestion

@nbolton's proposal in this thread — running the core as a user agent rather than spawning it from the GUI — would also solve the lifetime problem, since launchd would own the core's lifecycle instead of the GUI. Short of that, having the GUI reliably terminate its core on exit (including on signal paths) would remove the accumulation.

Happy to run any diagnostic you'd like on a machine where this reproduces consistently.
